config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :projects
  resources :userprojects
  resources :tasks
  resources :comments
  get '/cancel/:id', to: 'userprojects#cancel', as: :cancel
  # get '/index', to: 'searches#index', as: 'index'
  get '/search', to: 'userprojects#search', as: 'search'
  root 'users#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

# This is Application record
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

# This is about Comment model
class Comment < ApplicationRecord
  validates_uniqueness_of :comment, scope: :task_id
  validates :comment, :user_id, :task_id, presence: true
  belongs_to :user
  belongs_to :task
end

app/models/project.rb
# frozen_string_literal: true

# This is about Project model
class Project < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :userprojects
  has_many :users, through: :userprojects
  has_many :tasks, dependent: :destroy
end

app/models/task.rb
# frozen_string_literal: true

# This is about Task model
class Task < ApplicationRecord
  validates_uniqueness_of :description
  validates :description, :user_id, :project_id, :assigned_by, presence: true
  belongs_to :project
  belongs_to :user
  has_many :comments
end

app/models/user.rb
# frozen_string_literal: true

# This is about User model
class User < ApplicationRecord
  has_many :userprojects
  has_many :projects, through: :userprojects, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :comments, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/userproject.rb
# frozen_string_literal: true

# This is about Userproject model
class Userproject < ApplicationRecord
  validates_uniqueness_of :user_id, scope: :project_id
  validates :role, :user_id, :project_id, presence: true
  belongs_to :user
  belongs_to :project
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# This is Apllicationcontroller
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

# This is about Commentscontroller
class CommentsController < ApplicationController
  def index
    @userproject = Userproject.find(params[:id])
    @comments = Comment.where(user_id: @userproject.user_id)
  end

  def new
    @task = Task.find(params[:id])
    @comment = Comment.new(user_id: @task.assigned_by, task_id: @task.id)
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to @comment
    else
      render action: 'new'
    end
  end

  def show
    @comment = Comment.find(params[:id])
  end

  private

  def comment_params
    params.require(:comment).permit(:comment, :user_id, :task_id)
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

# This is about Projectscontroller
class ProjectsController < ApplicationController
  before_action :authenticate_user!

  def index
    @userproject = current_user.userprojects
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

# This is about Taskscontroller
class TasksController < ApplicationController
  before_action :authenticate_user!

  def index
    @userproject = Userproject.find(params[:id])
    @tasks = Task.where(user_id: @userproject.user_id,
                        project_id: @userproject.project_id)
  end

  def new
    @userproject = Userproject.find(params[:id])
    @users = Userproject.where(project_id: @userproject.project_id)
    @user_id = []
    @users.each do |user|
      @user_id << user.user_id
    end
    @task = Task.new(project_id: @userproject.project_id,
                     assigned_by: @userproject.user_id)
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to @task
    else
      redirect_back fallback_location: root_path, notice: 'Give correct values'
    end
  end

  def show
    @task = Task.find(params[:id])
  end

  private

  def task_params
    params.require(:task).permit(:description, :project_id, :user_id,
                                 :assigned_by)
  end
end

app/controllers/userprojects_controller.rb
# frozen_string_literal: true

# This is about userprojectscontroller
class UserprojectsController < ApplicationController
  before_action :set_userproject, only: %i[show destroy]
  before_action :authenticate_user!

  def index
    @userprojects = Userproject.where(project_id: params[:id],
                                      user_id: current_user.id)
  end

  def new
    @user = Userproject.find(params[:id])
    if @user.role == 'Admin'
      @role = [['Select', ''], 'Project manager', 'Team lead', 'Developer']
    elsif @user.role == 'Project manager'
      @role = [['Select', ''], 'Team lead', 'Developer']
    elsif @user.role == 'Team lead'
      @role = ['Developer']
    end
    @userproject = Userproject.new(project_id: @user.project_id)
  end

  def create
    @userproject = Userproject.new(userproject_params)
    @role = @userproject.role
    if @userproject.save
      redirect_to @userproject
    else
      redirect_back fallback_location: userprojects_path,
                    notice: 'Give correct values'
    end
  end

  def show; end

  def search
    @user = []
    if params[:user_id] && params[:description].blank?
      @works = Task.where('project_id = ?', params[:project_id])
      @tasks = @works.where(user_id: params[:user_id])
    elsif params[:description] && params[:user_id] == ''
      @works = Task.where('project_id = ?', params[:project_id])
      @tasks = @works.where('description ilike ?', "%#{params[:description]}%")
    else
      @works = Task.where('project_id = ? and description ilike ?',
                          params[:project_id], "%#{params[:description]}%")
      @tasks = @works.where(user_id: params[:user_id])
    end
    @tasks.each do |task|
      user_id = task.user_id
      email_id = User.find(user_id).email
      @user << {email: email_id, description: task.description, user_id: task.user_id,
                assigned_by: task.assigned_by, project_id: task.project_id}
    end
    render :search
  end

  def destroy
    @user = Userproject.find_by(id: @userproject.id)
    @task = Task.where(user_id: @user.user_id, project_id: @user.project_id)
    @task.destroy_all
    @userproject.destroy
    respond_to do |format|
      format.html { redirect_to userprojects_url(id: @userproject.project_id), notice: 'Userproject was successfully destroyed.' }
    end
  end

  def cancel
    @userproject = Userproject.find(params[:id])
    @cancel_user = Userproject.where(project_id: @userproject.project_id)
  end

  private

  def set_userproject
    @userproject = Userproject.find(params[:id])
  end

  def userproject_params
    params.require(:userproject).permit(:role, :user_id, :project_id)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# This is about Userscontroller
class UsersController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# This is about Application helper
module ApplicationHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/projects_helper.rb
# frozen_string_literal: true

# This is about Project helper
module ProjectsHelper
end

app/helpers/tasks_helper.rb
# frozen_string_literal: true

# This is about Task helper
module TasksHelper
end

app/helpers/userprojects_helper.rb
# frozen_string_literal: true

# This is about Userproject helper
module UserprojectsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

# This is about User helper
module UsersHelper
end

app/views/comments/index.html.erb
<% if @comments == [] %>
  <p> No comments found</p>
<% else %>
  <% @comments.each do |comment| %>

    <% task = Task.find_by(id: comment.task_id) %>
    <p>
      <strong> Task Description : </strong>
      <%= task.description %>
    </p>

    <p>
      <strong>Comment:</strong>
      <%= comment.comment %>
    </p><br>
  <% end %>
<% end %>
<%= link_to 'Back', userprojects_path(id: @userproject.project_id) %>

app/views/comments/new.html.erb
<%= form_for(@comment) do |form| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this userproject from being saved:</h2>

      <ul>
        <% @comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id %>
  </div>

  <div class="field">
    <%= form.hidden_field :task_id %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit' %>
  </div>
<% end %>

app/views/comments/show.html.erb
<%= form_for(@comment) do |form| %>

  <p>
    <strong>Comment:</strong>
    <%= @comment.comment %>
  </p>

  <p>
    <strong>Assigned To:</strong>
    <%= @comment.user_id %>
  </p>

<% end %>
<%= link_to 'Back', userprojects_path(id: @userproject.project_id) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myproject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/projects/index.html.erb
<h1>Projects</h1>
<% @userproject.all.each do |userproject| %>
    <table>
      <tr>
        <td>Project Id: <%= userproject.project_id %></td>
        <td><%= link_to 'Show', userprojects_path(id: userproject.project_id) %>
        <% if userproject.role == 'Admin' %>
          <td><%= link_to 'Destroy', cancel_path(id: userproject.id) %></td>
        <% end -%>
      </tr>
    </table>
<% end -%>
<%= link_to 'Back', users_path %>

app/views/tasks/index.html.erb
<% if @tasks == [] %>
  <p> No task assigned</p>
<% else %>
  <% @tasks.each do |task| %>
    <p>
      <strong>Task Description:</strong>
      <%= task.description %>
    </p>

    <p>
      <strong>Assigned By:</strong>
      <%= task.assigned_by %>
    </p>
    <br>
    <% if task.user_id == current_user.id %>
      <%= link_to 'Ask Questions?', new_comment_path(id: task.id) %><br>
    <% end %>
  <% end %>
<% end %>
<br>

<%= link_to 'Back', userprojects_path(id: @userproject.project_id) %>

app/views/tasks/new.html.erb
<h1>Tasks</h1>
<%= form_for(@task) do |form| %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :assigned_to %>
    <%= form.select :user_id, @user_id %>
  </div>

  <div class="field">
    <%= form.hidden_field :project_id, readonly: true %>
  </div>

  <div class="field">
    <%= form.hidden_field :assigned_by, readonly: true %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit' %>
  </div>
<% end %>
<%= link_to 'Back', userprojects_path(id: @userproject.project_id) %>

app/views/tasks/search.html.erb
<% if @tasks == [] %>
  <p> No task found</p>
<% else %>
  <% @tasks.each do |task| %>
    <p>
      <strong>Task Description:</strong>
      <%= task.description %>
    </p>

    <p>
      <strong>Assigned By:</strong>
      <%= task.assigned_by %>
    </p>

    <p>
      <strong>Assigned To:</strong>
      <%= task.user_id %>
    </p>

    <p>
      <strong>Project Id:</strong>
      <%= task.project_id %>
    </p><br>
  <% end %>
<% end %>

app/views/tasks/show.html.erb
<p>
  <strong>Task Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Assigned To:</strong>
  <%= @task.user_id %>
</p>

app/views/userprojects/cancel.html.erb
<h3> Project was successfully deleted </h3>
<% @cancel_user.destroy_all %>
<%= link_to 'Back', projects_path %>

app/views/userprojects/index.html.erb
<% @userprojects.each do |userproject| %>
  <%= form_tag(search_path, :method => "get", remote: true) do %>
    Task : <%= search_field_tag :description, params[:description], id: 'task_id' %>
    <% @users = Userproject.where(project_id: userproject.project_id) %><br>
    <%= hidden_field_tag :project_id, userproject.project_id, id: 'project_id' %>
    <br>User Id : <%= collection_select :task, :user_id, @users, :user_id, :user_id, {:prompt => true}, :multiple => true, id: 'user_id' %><br>
    <br><%= button_tag "search" %>
  <% end %><br>
  <div id="search-results">
  </div><br>

  <script type="text/javascript">
    $( document ).ready(function() {
      $("button").click(function() {
        var Task_id = $('#task_id').val();
        var Project_id = $('#project_id').val();
        var User_Id = $('#user_id').val();
        $.ajax({
          type: 'GET',
          url: "/search",
          dataType : 'json',
          data:{ project_id: Project_id, description: Task_id, user_id: User_Id },
          success: function(results){
            if (results.length == 0) {
              $('#table').hide();
              $('#search-results').append("No results found!!!");
            }
            else {
              $.each(results, function(i, data){
                $('#table').hide();
                $('#search-results').append("<strong>Email : "+data.email+'</strong>'+'<br>'+"Task Description : "+data.description+'<br>'+"Assigned By : "+data.assigned_by+'<br><br>');
              });
            }
          },
        });
      });
    });
  </script>

  <div id = 'table'>
    <table>
      <tbody>
        <%if userproject.role =='Admin' || userproject.role =='Project manager' || userproject.role =='Team lead' %>
          <%= link_to 'New Userproject', new_userproject_path(id: userproject.id) %><br><br>
        <% end -%>
        <%= link_to 'Assign task to user', new_task_path(id: userproject.id) %><br><br>
        <%= link_to 'Assigned Task', tasks_path(id: userproject.id) %><br><br>
        <%= link_to 'Comments', comments_path(id: userproject.id) %><br><br>
        <% if userproject.role == 'Admin' %>
          <tr>
            <td><h4>Project manager :</h4></td>
            <% Userproject.all.each do |u| %>
              <% if u.role == 'Project manager' && u.project_id == userproject.project_id %>
              <tr>
                <td>User Id : <%= u.user_id %></td>
                <td><%= link_to 'Task', tasks_path(id: u.id) %>
                <td><%= link_to 'Destroy', u, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
              <% end -%>
            <% end -%>
          </tr>
          <tr>
            <td><h4>Team lead :</h4></td>
            <% Userproject.all.each do |u| %>
              <% if u.role == 'Team lead' && u.project_id == userproject.project_id %>
              <tr>
                <td>User Id : <%= u.user_id %></td>
                <td><%= link_to 'Task', tasks_path(id: u.id) %>
                <td><%= link_to 'Destroy', u, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
              <% end -%>
            <% end -%>
          </tr>
          <tr>
            <td><h4>Developer :</h4></td>
            <% Userproject.all.each do |u| %>
              <% if u.role == 'Developer' && u.project_id == userproject.project_id %>
              <tr>
                <td>User Id : <%= u.user_id %></td>
                <td><%= link_to 'Task', tasks_path(id: u.id) %>
                <td><%= link_to 'Destroy', u, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
              <% end -%>
            <% end -%>
          </tr>

          <% elsif userproject.role == 'Project manager' %>
          <tr>
            <td><h4>Team lead :</h4></td>
            <% Userproject.all.each do |u| %>
              <% if u.role == 'Team lead' && u.project_id == userproject.project_id %>
              <tr>
                <td>User Id : <%= u.user_id %></td>
                <td><%= link_to 'Task', tasks_path(id: u.id) %>
                <td><%= link_to 'Destroy', u, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
              <% end -%>
            <% end -%>
          </tr>
          <tr>
            <td><h4>Developer :</h4></td>
            <% Userproject.all.each do |u| %>
              <% if u.role == 'Developer' && u.project_id == userproject.project_id %>
              <tr>
                <td>User Id : <%= u.user_id %></td>
                <td><%= link_to 'Task', tasks_path(id: u.id) %>
                <td><%= link_to 'Destroy', u, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
              <% end -%>
            <% end -%>
          </tr>

          <% elsif userproject.role == 'Team lead' %>
          <tr>
            <td><h4>Developer :</h4></td>
            <% Userproject.all.each do |u| %>
              <% if u.role == 'Developer' && u.project_id == userproject.project_id %>
              <tr>
                <td>User Id : <%= u.user_id %></td>
                <td><%= link_to 'Task', tasks_path(id: u.id) %>
                <td><%= link_to 'Destroy', u, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
              <% end -%>
            <% end -%>
          </tr>

          <% elsif userproject.role == 'Developer' %>
            <br>User Id : <%= userproject.user_id %>
        <% end -%>
      </tbody>
    </table>
  </div>
<% end -%>
<%= link_to 'Back', projects_path %>

app/views/userprojects/new.html.erb
<h1>New Userproject</h1>
<%= form_for(@userproject) do |form| %>
  <div class="field">
    <%= form.label :role %>
    <%= form.select :role, @role %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :project_id %>
    <%= form.text_field :project_id, readonly: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<%= link_to 'Back', userprojects_path(id: @userproject.project_id) %>

app/views/userprojects/show.html.erb
<p>
  <strong>Role:</strong>
  <%= @userproject.role %>
</p>

<p>
  <strong>User:</strong>
  <%= @userproject.user_id %>
</p>

<p>
  <strong>Project:</strong>
  <%= @userproject.project_id %>
</p>

<%= link_to 'Back', userprojects_path(id: @userproject.project_id) %>


<% if @tasks == [] %>
  <p> No task assigned</p>
<% else %>
  <% @tasks.each do |task| %>
    <p>
      <strong>Task Description:</strong>
      <%= task.description %>
    </p>

    <p>
      <strong>Assigned By:</strong>
      <%= task.assigned_by %>
    </p>
    <br>
    <% if task.user_id == current_user.id %>
      <%= link_to 'Ask Questions?', new_comment_path(id: task.id) %><br>
    <% end %>
  <% end %>
<% end %>
<br>
<%= link_to 'Back', userprojects_path(id: @userproject.project_id) %>

app/views/users/index.html.erb
<h1>Home</h1>
<% if user_signed_in? %>
  <%= button_to 'Project', projects_path(id: current_user.id), method: :get %><br>
  <%= button_to 'Logout', destroy_user_session_path, method: :delete %>
<% else %>
  <%= button_to 'Signup', new_user_registration_path, method: :get %><br>
  <%= button_to 'Login', new_user_session_path, method: :get %>
<% end %>